### ISSUE TITLE
How to represent delegated ctor initializers?

### ISSUE THREAD

**Issue by Xazax-hun** [GabrielDosReis/ipr#157]
E.g.

```
struct Foo
{
    Foo(int);
    Foo(double) : Foo(5) {}
};
```

**Comment by GabrielDosReis** [comment]
Constructor definitions have their "initializers" are given by `Ctor_body` where the [_ctor-initializer_](https://eel.is/c++draft/class.base.init#nt:ctor-initializer) is given by the `inits()` and the body of the constructor is given by `block()`.  There is no separate node for a delegating constructor because that is a property of the implementation, not of the declaration of the constructor: [if the _ctor-initializer_ contains a call to a constructor from the same class, then you have a delegating constructor](https://eel.is/c++draft/class.init#class.base.init-6).  Here the _ctor-initializer_ is represented exactly the same way that you would represent initialization of a base-class subobject.

What are the issues you were running into?

**Comment by Xazax-hun** [comment]
Looks good to me, and in fact the implementation I am working on is doing just that (using he same representation as base-class subobjects). I wanted to double check, if that is OK.
