### ISSUE TITLE
need: implicit member access

### ISSUE THREAD

**Issue by GorNishanov** [GabrielDosReis/ipr#27]
```
struct S {
   int x;

   void f() {
       x = 2; // <-- implicit member access node
       this -> x = 3; // represented using (implicit object parameter => x)
   }
};
```

**Comment by GabrielDosReis** [comment]
This issue really matters the most only for templated code.  In fully elaborated function definition, the elaboration phase will infer the implicit member access transformation and will represent the code with `this` for `Arrow`.

Proposed resolution: Make `Arrow::base()` return an `Optional<Expr>, with the following meaning.
   - if `base()` is "empty" then it means the implicit object was not explicitly specified at the source level (templated code)
   - otherwise, that nodes represents `this`.

Thoughts?

**Comment by GorNishanov** [comment]
I am not sure. If we have the information about the base(), nulling it out to serve as flag seems suboptimal.

My interpretation of the newly introduced "This" expression is that it was meant to represent implicit this node, thus for the example cited in this issue, there is no need to alter `Arrow` expression:

```c++
struct X 
{
   int x;
   void f() { // has explicit "this" first parameter in the IPR
      x = 5; // This -> x = 5;
      this->x = 5; // Id_expr("this") -> x = 5;
   }
};
```

However your question is relevant, if we want to distinguish between explicit and implicit use of `this` in the non static member initializers, i.e:

```c++
struct S {
   int x;
   int y = x + this->x;
};
```

In this case, we have no way to distinguish between `x` and `this->x`, since we need to use `This` node both for explicit and implicit use.

An alternative to what you suggested, is to introduce a child class of `Arrow`, say, `Implicit_arrow` that would be used to disambiguate between `x` and `this->x`.

The underlying principle is that if you have the useful information, we should not remove it (set to nullptr) to serve as a flag.

**Comment by GabrielDosReis** [comment]
The proposal does not throw away any information that is available.  The null `base()` is only to be constructed in templated code.  However, as per our conversation from yesterday let's close this issue until it becomes clear there is any actual need here.
