### ISSUE TITLE
Infinite recursion when printing XPR?

### ISSUE THREAD

**Issue by Xazax-hun** [GabrielDosReis/ipr#68]
Since the latest commits on master the PR to add unit tests is failing on the CI: https://github.com/GabrielDosReis/ipr/pull/58

The test is the following:
```
TEST(TestIO, GlobalConstIntWithInit) {
  using namespace ipr;
  impl::Lexicon lexicon{};
  impl::Module m{lexicon};
  impl::Interface_unit unit{lexicon, m};

  impl::Scope* global_scope = unit.global_scope();

  const Name* name = lexicon.make_identifier("bufsz");
  auto& type = lexicon.get_qualified(Type_qualifier::Const, lexicon.int_type());
  impl::Var* var = global_scope->make_var(*name, type);
  var->init = lexicon.make_literal(lexicon.int_type(), "1024");

  std::stringstream ss;
  Printer pp{ss};
  pp << unit;
  EXPECT_GT(ss.str().size(), 0);
}
```

Attaching gdb shows that it is probably a stack overflow when printing the XPR representation (I have a 150k+ deep call stack).
This test used to work before https://github.com/GabrielDosReis/ipr/commit/ea3f5c6bdf0044ec98422dbb3f2bc0b725d43f38

This test is based on some examples from the documentation. So we either:
* Need to update the documentation to explain how IPR can be used, or
* We have a bug that needs to be fixed and that could have been prevented by adding some tests.

**Comment by GabrielDosReis** [comment]
Thanks for the report.  I agree that this issue should have been spotted earlier if those tests were running as part of the PR check.  The solution to the root cause is actually a set of actions - not just one thing:
   1. Formally (re)define the XPR grammar - there used to be two parsers for the XPR, a recursive decent parser and a Yacc-based parser.  The two versions were to ensure that we got things right. I don't know what happened to either of them.  (But you can still see comments alluding to them in the remaining source code).  At some point, the original Yacc-based grammar was forked and mutated in many ways by various people in different directions.  The upshot is we don't actually know what the "XPR" is anymore.  That grammar spec needs to be recreated.
   2. We need a non-XPR external representation of the IPR that allows "raw" faithful presentation of the data structures.  I used to have an s-expression printer.  See my comments in the feedback to the test infrastructure framework
   3. The change being a breaking change, I fully expect any thing that depended on a Name being an expression to be broken, so I wouldn't call this a "bug" -- but, definitely the printer should be fixed.
   4. We need to have the test infrastructure in
   5. The documentation needs update


Note that not one single action fixes the root cause, and it isn't an issue of pitting against tests.  It was a deliberate breaking change.

**Comment by GabrielDosReis** [comment]
I pushed the wrong local branch
