### ISSUE TITLE
Should the As_type::expr() of a built-ins point to itself?

### ISSUE THREAD

**Issue by d-winsor** [GabrielDosReis/ipr#71]
In the PR #67 `Name` was moved out of the `Expr` hierarchy but in the process the type expr of a BuiltIn was changed to itself. This caused the infinite recursion meantioned in Bug #68.

```
As_type {
  Name = 'int'
  Expr= As_type {
    Name = 'int'
    Expr= {...} }}
```

Using `As_type` for built-ins made sense when `Name` itself was an `Expr` because it was giving meaning to the use of a `Name` Node. Now built-ins are the use of the expr of themselves, this seem confusing.

Consider adding a new type node `Primitive` at which point you can remove the Linkage from `As_type` as from my understanding it only aimed to serve "extended built-in" types.

**Comment by GabrielDosReis** [comment]
Yes, the core of the issue is the same as #68.  There is no real confusion here.  The code that depended on the previous behavior of `As_type` need updating (hence the change in #67 explicitly labeled breaking change), but I don't think there is any confusion of to the meaning or the behavior.

A notion of `Primitive` was considered many times (long before this change) and consistently rejected as both limited, insufficient, and not general enough.  That the _builtin types_ become a fix point of the the functor As_type: Expr -> Expr actually expresses the logical and semantic of being built-in: there is no further elaboration as to what its meaning is made of.

And in general, the `Type` hierarchy is intrinsically a graph, a cycle is to be expected, so a textually representation of the internal representation that does not make provision for cycles is expected to be faulty.

**Comment by BjarneStroustrup** [comment]
On 9/12/2020 8:02 PM, Gabriel Dos Reis wrote:
>
> Yes, the core of the issue is the same as #68 
> <https://github.com/GabrielDosReis/ipr/issues/68>. There is no real 
> confusion here. The code that depended on the previous behavior of 
> |As_type| need updating (hence the change in #67 
> <https://github.com/GabrielDosReis/ipr/pull/67> explicitly labeled 
> breaking change), but I don't think there is any confusion of to the 
> meaning or the behavior.
>
> A notion of |Primitive| was considered many times (long before this 
> change) and consistently rejected as both limited, insufficient, and 
> not general enough. That the /builtin types/ become a fix point of the 
> the functor As_type: Expr -> Expr actually expresses the logical and 
> semantic of being built-in: there is no further elaboration as to what 
> its meaning is made of.
>
> And in general, the |Type| hierarchy is intrinsically a graph, a cycle 
> is to be expected, so a textually representation of the internal 
> representation that does not make provision for cycles is expected to 
> be faulty.
>
Nicely put.
