### ISSUE TITLE
Empty_stmt feels unnatural, Expr/Stmt relationship flipped?

### ISSUE THREAD

**Issue by Xazax-hun** [GabrielDosReis/ipr#81]
I have some trouble wrapping my head around `Empty_stmt`.

My first problem is that it is derived from `Expr_stmt`. There are multiple problems with this in my opinion:
- `Empty_stmt` is not a `Unary` but a `Nullary` thing.
- `Empty_stmt` is not an Expression. 
- `Unary` was designed to be the base class of the final class as it expects to set the category number. This makes it challenging to add a category number to `Empty_stmt`.

My other problem with `Empty_stmt` is the naming, I think we should follow the C++ standard unless we have a strong reason to diverge (e.g. making something more general). In the C++ standard, it is called `Null_stmt`: https://eel.is/c++draft/stmt.expr

But I think this uncovers a bigger difference between the C++ standard and IPR. Namely, the relation between statements and expressions. In IPR a statement is derived from an expression (so a statement is an expression). In Clang it is the other way around, expressions are derived from statements (so expression is a statement). According to the C++ standard, neither of them are correct. We have expression-statements (which are statements), those wrap expressions.  If we want to put them in the same inheritance hierarchy, I think Clang's view is closer to reality. And the main reason why I think that because this is very similar to the relationship between declarations and statements. They are different according to the standard, but we have declaration statements (that are statements), those wrap declarations. And in IPR, declarations inherited from statements (so declarations are statements). 

So I think the decl-statements and expr-statements are very similar, yet I feel like IPR does handle them the opposite way. I suggest flipping the inheritance between expressions and statements. (Or alternatively, keep all those hierarchies separate and use SUM types whenever multiple types of entities can occur at the same place, like at an if expression's condition.)

What do you think? Do I miss something?

**Comment by GabrielDosReis** [comment]
1. I don't understand the comment that `Empty_stmt` ia not a `Unary` but a `Nullary` thing.

2.  What's the problem with `Empt_stmt` not be an Expression?  Why does it need to be?


> But I think this uncovers a bigger difference between the C++ standard and IPR.

IPR wasn't designed -- nor is it its goal -- to mimic ISO C++ exactly with its barnacles.  Rather, it aimed to be a regular data structure defining an expression-based language that happens to contain ISO C++ and that offers more regularity.

IPR was designed and implemented in 2004-2005, long before Clang was even conceived (and some of the Clang authors were aware of IPR).  IPR does not have a Clang envy, does aim it to be a Clang data structure, nor the data structure of a particular compiler.  This point is worth emphasizing, because it guides everything else.  If a particular compiler happens to adopt it as its internal data structure, great; but it isn't operating under the assumption of being a given compiler data structure or to copy Clang.  Rather IPR aims to be a compiler-neutral data structure aiming to enable semantics-based analyses and transformations of C++ programs.

Many of the design choices regarding the choices of declaration/statements/expressions are in the `ipr/interface` file.

**Comment by Xazax-hun** [comment]
>     1. I don't understand the comment that `Empty_stmt` is not a `Unary` but a `Nullary` thing.

I think of `Empty_stmt` like a leaf node without any children. And I think of `Unary` as an internal node with one child. This is why it felt unnatural to me to make `Empty_stmt` a subclass of `Unary`. And coincidentally, this makes it harder to give it a `Category_number`.

>     2. What's the problem with `Empty_stmt` not be an Expression?  Why does it need to be?

Sorry for the unclear point. Currently, everything is an expression in IPR, and I was wondering whether it is good to include things like `Empty_stmt` that has no meaningful type or value. When the user sees the factory function for this node, it might be puzzling that it expects a type. But I think this is not really a problem, it was just unusual. My main concern is, these unusual decisions can possibly hinder adoption. I think keeping the flexibility under the hood might be a good idea, but we could expose factory functions that are closer to the expectations of a C++ tool developer. That way we could both define a superset of C++ while we could provide a set of factories that are specifically tailored to C++.

>  IPR does not have a Clang envy, does aim it to be a Clang data structure, nor the data structure of a particular compiler.

I understand this point, I just find it useful to compare solutions. That helps me argue about the advantages and disadvantages of both. In this particular case, I would argue that Clang's approach makes its AST more inconvenient to use in certain scenarios. But I was not sure, whether IPRs approach is better (but admittedly without any access to a client of IPR, I have no data to back that up).

**Comment by BjarneStroustrup** [comment]
Nicely put

**Comment by GabrielDosReis** [comment]
> But I think this is not really a problem, it was just unusual.

The IPR design encourages a bit more "thinking out of the box", and as such is not the usual compiler data structure that focuses on the minimal thing required or convenient to implement a familiar compiler.  If you look at the "regularize void movement", you would see that this is not actually not that usual.
